### ISSUE TITLE
doesn't include api reference?

### ISSUE THREAD

**Issue by sedlund** [dohsimpson/kubernetes-doc-pdf#8]
I don't see the api reference docs in these PDF's

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/

**Comment by dohsimpson** [comment]
The API Reference is actually a piece of cake, since it's a single page, you can just print as PDF.

One thing that worries me was whether the printed PDF without the bookmarks is going to be hard to navigate. But this was not the case, as the left-hand side table of content is kept and the anchor worked great to navigate the PDF document.

Attached a PDF I printed from Safari.
[Kubernetes API Reference Docs.pdf](https://github.com/dohsimpson/kubernetes-doc-pdf/files/4171544/Kubernetes.API.Reference.Docs.pdf)
